language: node_js
node_js:
- '12.13'
deploy:
  provider: npm
  email: EMAIL
  api_key: NPM_TOKEN
  tag: next
env:
  global:
  - secure: MnOIka/17oK5ihLvl8P9/bcljxAmiS/CkJG2tNjldFPU7M60GQp+6F9nXwkbPLSqeawPpz65hHqvqs/kQdvhP7hE/vpSXxoXnxnfOWouL2y3PG06qK7g6RMmEb77WEQcXId0TyVB/n5ZLOybHFkcjJqaOKwITZ7pXgNC99TXWA2Vx/kZCwgTXcIomv98q7sXsZSQXmvsk3Hlcrfa4pxrVQnaqy2WqlLNEMiOoFRMPpbABCg0X5uI3Ek7898XOh92oa/9r7QXvdaiPRGOnX3vyH6l4FaezYxYGkyzutpUdosB4simFeIo6JRbNz9IGX+ninT2VPx7zYNV47C9E8DWTpOGzcv58Guvn26crtVwZyCUkDZQR7QC/EkqknSFLXdlVTw7oQE+UDXG0n9aKEVoF7tbnfnBWg3NMJGM3DOAwx6Dc6Ky/CRj7dBgoFIUxpy2JBMTIOqwugLxEN1RncMhyDl3C4peU4zojAuVdnnLjU0zQ4E3rJCZchP0vfLqFDA1IKhELzZLs/eE5FCCFG8/jJABWxxw3YPyOxJxoHUKoS0yPOaf+Nyi9/Q/qXWPFsY/kMrLl/tYIEUrD8c9MUQ9WfBQe71KYPQuIa39Ge45T6Z1TL7k8Opdnfoc6zSI/NSBEmvMWWOGTuLitlLxbJ0u4KV696rjY4riLrQPwEPiCWk=
  - secure: pLAEWk1+0JhUxZLo4RpOQv0I0uH6CD7xX5brwTRJFVljWnfdDBcidxuRNB13ODUXIlJ03kU67DFKi82pC2W7cL4ZkhmJCrwVbXSWGYDY4UkGoQZpRyQ35N8k5xudOOX8jnt+e8emZrMRLyVruzGGWu/ozM4sEVMtYgRbMj1QpojhBI+UsTRrY0SDEmE+4NBn1245V9xJXcoyd0NBkcTFpf1Elv3DA4lK/UzJCuwISADCVo9KgiI08NqDte8mUEAFGtSS+LTHhtpno4tNrSf2Uqlf9qSqNbsH/DPZMxDtZ//mW5fe3wgWkeK4qWTjpx8fK0lQhtVmrvDh/A94XG6E22lYzfe5K04DONWjHvKt0ikBJqeJGIe/38JKLyFzsESquTnIoLA17Opd4qqOkaSxm0RBbZJEzrnTHbkZE88PS8TZI69XJn/XkhWOH/x+r4dugsNGORPhHGqSWf74USUrQQeW9X76maeuR1/dKLcLvXLSJ5zT2noEmSZkdnEJzS1VIT3OXkakV7/jUsKjN9ifZNF/MO/6LbtavW5CLW64G4O9j64AsLZH5gc7LoJcEYuU6Go7va7UICT0uxO/ZbizumQgks7teU3LmOT8vabhWSr5g+DMEAWHOUCPnoviEEuulRXKKmAnj4YFozw/AuTTxka0KhropX/b4fiZv6y1kaI=
